Resources:
  ClimbsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "climb_id"
          AttributeType: "S"
        - AttributeName: "user_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "climb_id"
          KeyType: "RANGE"
        - AttributeName: "user_id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "climbs"