Resources:
  RoutesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "route_id"
          AttributeType: "S"
        - AttributeName: "isActive"
          AttributeType: "BOOL"
        - AttributeName: "location"
          AttributeType: "S"
        - AttributeName: "difficulty"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "isActive"
          KeyType: "HASH"
        - AttributeName: "route_id"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "routes"
      GlobalSecondaryIndexes:
        - IndexName: "RoutesByLocationIndex"
          KeySchema:
            - AttributeName: "location"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "RoutesByIsActiveIndex"
          KeySchema:
            - AttributeName: "isActive"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
